export default {
    defaultStyle: {
        ...theme.fonts.regular,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeNormal,
    },
    a:{
        ...theme.fonts.regular,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
        textDecorationLine:'none',
        textDecorationLine:'underline',
    },
    p:{
        ...theme.fonts.regular,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
        marginBottom:20,paddingBottom:0,
        textAlign:'left'
    },
    br:{
        height:1,
        backgroundColor:'#d00'
    },
    h1:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    h2:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    h3:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    h4:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    h5:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    h6:{
        ...theme.fonts.bold,
        marginBottom:10,
        color:theme.colors.textcolor,
        fontSize:theme.variables.fontSizeBig,
        textAlign:'left',
    },
    em:{
        fontStyle: 'italic',
    },
    i:{
        fontStyle: 'italic'
    },
    u:{
        ...theme.fonts.regular,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
        textDecorationLine:'underline',
    },
    b:{
        ...theme.fonts.bold,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
    },
    strong:{
        ...theme.fonts.bold,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
    },
    ul:{
        marginLeft:0,paddingLeft:0
    },
    li:{
        ...theme.fonts.regular,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
        marginLeft:2,
        textAlign:'left',
    },
    ol:{
        ...theme.fonts.regular,
        fontSize:theme.variables.fontSizeNormal,
        color:theme.colors.textcolor,
        marginLeft:2,
        textAlign:'left',
    },
    iframe:{width:'100%',height:130},
};
